### ISSUE TITLE
Discussion: our software is only as good as our process

### ISSUE THREAD

**Issue by q0rban** [Lullabot/engineering-values#9]
For discussion: is there something here to capture in our engineering values? That even with the best engineering values, we can only achieve what the process allows, and the process is controlled by the organization… or something?

> "Programmers don’t make software. We may think we do, we might wish we did, but we don’t. Organizations make software. Despite your values and disciplines and practices, the health of the organization will be an upper bound on the health of your code."

- https://einarwh.wordpress.com/2020/04/05/death-of-a-craftsman/

**Comment by deviantintegral** [comment]
There's in interesting wrinkle in that with client work. I wonder if you could say that the upper bound isn't the health of the organization, but "minimum of the health of all organizations on the project".

I could see adding "Our software is only as good as a process" as a sentence in "Excellence balances perfect and done".
